# Dump the EC curve constants + remaining KDF primitives.
# KDF (FUN_100107650): key = X(priv*staticPt) XOR X(priv*stickPub)
#   priv generated by FUN_1004032b0 (random mod n, n at DAT_100cf5c10)
#   scalarmult = FUN_1003ff3c0, prime p at DAT_100cf5bf0, gen G at DAT_100cf5c30
# @category Stick

import os, re, struct
from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor

OUT_DIR = os.path.join(os.path.dirname(getSourceFile().getAbsolutePath()), 'out-curve')
try: os.makedirs(OUT_DIR)
except OSError: pass

prog = currentProgram
fm = prog.getFunctionManager()
af = prog.getAddressFactory()
mem = prog.getMemory()
monitor = ConsoleTaskMonitor()
decomp = DecompInterface()
decomp.openProgram(prog)
def addr(a): return af.getDefaultAddressSpace().getAddress(a)

def rd(a, n):
    buf = bytearray(n)
    try:
        mem.getBytes(addr(a), buf)
    except Exception as e:
        return None
    return bytes(buf)

def hexdump(label, a, n, out):
    b = rd(a, n)
    out.write('\n== %s @ 0x%x (%d bytes) ==\n' % (label, a, n))
    if b is None:
        out.write('  (unreadable)\n'); return
    for i in range(0, n, 16):
        row = b[i:i+16]
        hx = ' '.join('%02x' % x for x in row)
        out.write('  +%03x  %-47s\n' % (i, hx))
    # also as little-endian 256-bit ints, 32B at a time
    for i in range(0, n - 31, 32):
        words = struct.unpack('<4Q', b[i:i+32])
        be = (words[3] << 192) | (words[2] << 128) | (words[1] << 64) | words[0]
        out.write('  [%03x] LE-as-256bit = 0x%064x\n' % (i, be))

def decompile(func):
    res = decomp.decompileFunction(func, 240, monitor)
    if res.decompileCompleted():
        return res.getDecompiledFunction().getC()
    return '(decompile failed: %s)\n' % res.getErrorMessage()

def dump_fn(fp, label, out):
    f = fm.getFunctionAt(addr(fp)) or fm.getFunctionContaining(addr(fp))
    if f is None:
        out.write('\n==== %s 0x%x : NO FUNCTION ====\n' % (label, fp)); return
    out.write('\n==== %s : %s @ %s (%d bytes) ====\n' %
              (label, f.getName(True), f.getEntryPoint(),
               f.getBody().getNumAddresses()))
    callees = sorted(set('%s@%s' % (c.getName(True), c.getEntryPoint())
                         for c in f.getCalledFunctions(monitor)))
    out.write('callees: %s\n' % ', '.join(callees))
    out.write(decompile(f))

# ---- 1. constants ----
const = open(os.path.join(OUT_DIR, 'CONSTANTS.txt'), 'w')
# wide region covering prime, order, generator, a/b coefficients
hexdump('region_cf5b00', 0x100cf5b00, 0x300, const)
hexdump('DAT_100cf5bf0_prime?',   0x100cf5bf0, 0x20, const)
hexdump('DAT_100cf5c10_order_lo', 0x100cf5c10, 0x20, const)
hexdump('DAT_100cf5c30_generator',0x100cf5c30, 0x40, const)
hexdump('decoded_secret_cf8d11',  0x100cf8d11, 0x21, const)
hexdump('obfuscated_src_7b0490',  0x1007b0490, 0x21, const)
const.close()

# ---- 2. EC primitives + static-point builder ----
prim = open(os.path.join(OUT_DIR, 'PRIMITIVES.txt'), 'w')
for fp, label in [
    (0x100402560, 'EC_op_402560'),
    (0x100404fc0, 'EC_op_404fc0'),
    (0x1003ffc40, 'EC_pt_add_3ffc40'),
    (0x100400fd0, 'EC_pt_dbl_400fd0'),
    (0x1004061d0, 'EC_reduce_4061d0'),
    (0x100401c50, 'EC_op_401c50'),
    (0x100402ab0, 'static_point_builder_402ab0'),
    (0x1003f4530, 'cfb_key_install_3f4530'),
]:
    dump_fn(fp, label, prim)
prim.close()

# ---- 3. cipher vtable slots (vptr value 0x10095F838) ----
vt = open(os.path.join(OUT_DIR, 'VTABLE.txt'), 'w')
VTBL = 0x10095F838
vt.write('cipher secondary vtable @ 0x%x\n' % VTBL)
slots = {}
for off in range(0, 0x60, 8):
    b = rd(VTBL + off, 8)
    if b is None:
        vt.write('  +0x%02x : (unreadable)\n' % off); continue
    ptr = struct.unpack('<Q', b)[0]
    slots[off] = ptr
    f = fm.getFunctionAt(addr(ptr)) if ptr else None
    vt.write('  +0x%02x : 0x%x  %s\n' % (off, ptr, f.getName(True) if f else ''))
for off, label in [(0x20, 'vt20_net_exchange'),
                   (0x28, 'vt28_state_getter'),
                   (0x38, 'vt38_static_getter')]:
    ptr = slots.get(off)
    if ptr:
        dump_fn(ptr, label, vt)
vt.close()

print('dump-curve: done -> %s' % OUT_DIR)
